### ISSUE TITLE
Fix a few issue a technical mistakes in the website

### ISSUE THREAD

**Issue by CosmicFusion** [PikaOS-Linux/pikaos-site#1]
Text/Spelling Mistakes:
• The main header it says `linux` it would look better and more correct as `Linux®`
• in feature 1 its says `litte guy` instead of `little guy` also add `OwO` to the end of that
• feature 2 says `PikeOS`
• feature 4 says `upto date` instead of `up-to-date` and i think mean should be `means`
• feature 6 `are ppas` should be `Our PPAs`

Technical Mistakes and additions:
• Add link to our launchpad down there `https://launchpad.net/~pikaos`
• The side bar on mobile agents should auto retract when a button is pressed

**Comment by ferrreo** [comment]
Fixed
